version: '3'
services:
  wui:
    build: .
    volumes:
      - ./:/code
      - /code/node_modules
    ports:
      - 6060:6060

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1280
