name: Publish NPM Package

'on':
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: '15.x'
      - name: Install dependencies
        run: yarn install
      - name: Build project
        run: yarn build
      - name: Copy package.json
        run: cp -r package.json lib/
      - name: Publish to NPM
        run: yarn publish lib/ --non-interactive
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
